//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
       public int Id { get; set; }
        public string Name { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<int> Numer { get; set; }
        public Nullable<int> GrupaId { get; set; }
        public Nullable<int> StanowiskoId { get; set; }
        public Nullable<System.DateTime> BirthData { get; set; }
        public Nullable<int> Pesel { get; set; }
        public string Plec { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        public virtual Stanowisko Stanowisko { get; set; }
    }
}
